djangoshop/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import notifications


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
    #path('inbox/notifications/', include(notifications,namespace='notifications')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from ecomapp.views import *

urlpatterns = [
    path('',BaseView.as_view(), name='base'),
    path('change_item_qty/', change_item_qty, name='change_item_qty'),
    path('category/<str:category_slug>', CategoryView.as_view(), name='category_detail'),
    path('remove_from_cart/', RemoveFromCart.as_view(), name ='remove_from_cart'),
    path('add_to_cart/', AddToCart.as_view(), name ='add_to_cart'),
    path('product/<str:product_slug>', ProductView.as_view(), name='product_detail'),
    path('cart/', Cart.as_view(), name='cart'),
    path('checkout/',Checkout.as_view(),name='checkout'),
    path('order/',order_create_view, name='create_order'),
    path('make_order/', make_order_view, name='make_order'),
    path('thank_you/', TemplateView.as_view(template_name='ecomapp/thank_you.html'), name='thank_you'),
	path('account/', account_view, name='account'),
	path('registration/', registration_view, name='registration'),
	path('login/', login_view, name='login'),
	path('logout/', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
]

ecomapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone
import pytils
from time import time
import notifications
from django.contrib.auth.models import User
from PIL import Image
import os
import glob
from django.utils import timezone

def gen_slug(cls):

	title=str(cls.title)
	new_slug = pytils.translit.translify(slugify(title, allow_unicode=True))
	
	for i in cls.__class__.objects.all():
		if new_slug == i.slug:
		 	return new_slug + '-' + str(int(time())) 
	else:
		return new_slug

class Category(models.Model):

	title = models.CharField(max_length=100)
	slug = models.SlugField(blank=True)

	def __str__(self):
		return self.title
	def save(self, *args, **kwargs):
		
		if not self.id and not self.slug:
			self.slug = gen_slug(self)
		super().save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('category_detail', kwargs={'category_slug': self.slug})




class Brand(models.Model):

	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


def image_folder(instance, filename):
	filename = instance.slug + '.' + filename.split('.')[1]
	return "{0}/{1}".format(instance.slug, filename)


class Product(models.Model):

	category = models.ForeignKey(Category,on_delete=models.CASCADE)
	brand = models.ForeignKey(Brand,models.CASCADE)
	title = models.CharField(max_length=120)
	slug = models.SlugField()
	description = models.TextField()
	image = models.ImageField(upload_to=image_folder)
	price = models.DecimalField(max_digits=9, decimal_places=2)
	available = models.BooleanField(default=True)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('product_detail', kwargs={'product_slug': self.slug})
		

# def product_available_notification(sender, instance, *args, **kwargs):
# 	if instance.available:
# 		await_for_notify = [notification for notification in MiddlwareNotification.objects.filter(
# 			product=instance)]
# 		for notification in await_for_notify:
# 			notify.send(
# 				instance,
# 				recipient=[notification.user_name],
# 				verb='Уважаемый {0}! {1}, который Вы ждете, поступил'.format(
# 					notification.user_name.username,
# 					instance.title),
# 				description=instance.slug
# 				)
# 			notification.delete()


# post_save.connect(product_available_notification, sender=Product)	


class CartItem(models.Model):

	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	qty = models.PositiveIntegerField(default=1)
	item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

	def __str__(self):
		return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):

	items = models.ManyToManyField(CartItem, blank=True)
	cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

	
	def add_to_cart(self,product_slug):

		cart=self
		product= Product.objects.get(slug=product_slug)
		new_item, _ =CartItem.objects.get_or_create(product=product)
		for item in cart.items.all():
			if str(product_slug)==str(item.product.slug):
				new_item.qty+=1
				for i in range(10):
					print(new_item.qty)
				new_item.item_total= int(new_item.qty)* Decimal(new_item.product.price)
				new_item.save()
				cart.save()
				break

		else:
			new_item.item_total= Decimal(new_item.product.price)
			new_item.save()
			cart.items.add(new_item)
			cart.save()

	def remove_from_cart(self,product_slug):

		cart=self
		product = Product.objects.get(slug=product_slug)
		new_item, _ =CartItem.objects.get_or_create(product=product)


		for cart_item in cart.items.all():
			if cart_item.product == product:
				cart.items.remove(cart_item)
				new_item.delete()
				cart.save()


	def change_qty(self,qty,item_id):
		cart=self


		cart_item=CartItem.objects.get(id=int(item_id))
		cart_item.qty =int(qty)
		cart_item.item_total=int(qty)* Decimal(cart_item.product.price)
		cart_item.save()
		#переделать в отдельную функцию
		new_cart_total = 0.00
		for item in cart.items.all():
			new_cart_total += float(item.item_total)
		cart.cart_total = new_cart_total
		cart.save()

	def __str__(self):
		return str(self.id)



ORDER_STATUS_CHOICES = (
	('Принят в обработку', 'Принят в обработку'),
	('Выполняется', 'Выполняется'),
	('Оплачен', 'Оплачен')
)

class Order(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	items = models.ForeignKey(Cart,on_delete=models.CASCADE)
	total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	phone = models.CharField(max_length=20)
	address = models.CharField(max_length=255)
	buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), 
		('Доставка', 'Доставка')), default='Самовывоз')
	date = models.DateTimeField(auto_now_add=True)
	comments = models.TextField()
	status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

	def __str__(self):
		return "Заказ №{0}".format(str(self.id))




# class MiddlwareNotification(models.Model):

# 	user_name = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
# 	product = models.ForeignKey(Product,on_delete=models.CASCADE)
# 	is_notified = models.BooleanField(default=False)

# 	def __str__(self):
# 		return "Нотификация для пользователя {0} о поступлении товара {1}".format(
# 	   	self.user_name.username, 
# 	   	self.product.title
# 	   	)

ecomapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from decimal import Decimal
from django.shortcuts import render
from django.http import HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.contrib.auth import login, authenticate
from ecomapp.forms import OrderForm,RegistrationForm,LoginForm
from ecomapp.models import Category,Product,CartItem,Cart,Order
from django.views.generic import View
from django.contrib.auth.models import User
from ecomapp.utilits import *
#Объединить base_view,product_view,category_view в Base
# def base_view(request):
# 	cart=get_cart(request)
# 	categories = Category.objects.all()
# 	products = Product.objects.all()
# 	context = {
# 		'categories': categories,
# 		'products': products,
# 		'cart': cart
# 	}
# 	return render(request, 'ecomapp/base.html', context)


class BaseView(BaseMixin,View):
	template='ecomapp/base.html'
	#доработать!!!!!!!!!!!!!!
	def view_object_function(*args,**kwargs):
		products = Product.objects.all()
		new_context={'products':products}
		return new_context
				#product = Product.objects.get(slug=product_slug)
class ProductView(BaseMixin,View):
	template='ecomapp/product.html'
	def view_object_function(new_details,*args,**kwargs):
		product_slug=new_details.kwargs['product_slug']
		product = Product.objects.get(slug=product_slug)
		new_context={'product':product}
		return new_context
# def product_view(request, product_slug):
# 	cart=get_cart(request)
# 	product = Product.objects.get(slug=product_slug)
# 	categories = Category.objects.all()
# 	context = {
# 		'product': product,
# 		'categories': categories,
# 		'cart': cart,
# 	}
# 	return render(request, 'ecomapp/product.html', context)
class CategoryView(BaseMixin,View):
	template='ecomapp/category.html'
	def view_object_function(new_details,request,*args,**kwargs):
		category_slug=new_details.kwargs['category_slug']
		category = Category.objects.get(slug=category_slug)
		products_of_category = Product.objects.filter(category=category)
		#price_filter_type = request.GET.get('price_filter_type')
		new_context={'products_of_category': products_of_category,'category': category,}
		return new_context


# def category_view(request, category_slug):
# 	cart=get_cart(request)
# 	category = Category.objects.get(slug=category_slug)
# 	price_filter_type = request.GET.get('price_filter_type')
# 	for i in range(100):
# 		print(price_filter_type)
# 	products_of_category = Product.objects.filter(category=category)
# 	categories = Category.objects.all()
# 	context = {
# 		'category': category,
# 		'products_of_category': products_of_category,
# 		'cart': cart,
# 		'categories': categories,
# 	}
# 	return render(request, 'ecomapp/category.html', context)



#объединить в Cart
class Cart(CartMixin,View):
	template='ecomapp/cart.html'
# def cart_view(request):
# 	cart=get_cart(request)
# 	categories = Category.objects.all()
# 	context = {
# 		'cart': cart,
# 		'categories': categories
# 	}
# 	return render(request, 'ecomapp/cart.html', context)
class Checkout(CartMixin,View):
	template='ecomapp/checkout.html'
# def checkout_view(request):
# 	cart=get_cart(request)
# 	categories = Category.objects.all()
# 	context = {
# 		'cart': cart,
# 		'categories': categories
# 	}
# 	return render(request, 'ecomapp/checkout.html', context)
#Объединить add_to_cart_view,remove_from_cart_view,
#change_item_qty,checkout_view в Cart_actions'
class AddToCart(CartActionsMixin,View):
	def action(garbage,product_slug,cart):
		cart.add_to_cart(product_slug)
		reload_cart_cost(cart)
		return cart
# def add_to_cart_view(request):
# 	cart=get_cart(request)
# 	product_slug=request.GET.get('product_slug')
# 	#product = Product.objects.get(slug = product_slug)
# 	cart.add_to_cart(product_slug)
# 	reload_cart_cost(cart)
# 	return JsonResponse({'cart_total': cart.items.count(),
# 		'cart_total_price': cart.cart_total,})
class RemoveFromCart(CartActionsMixin,View):
	def action(garbage,product_slug,cart):
		cart.remove_from_cart(product_slug)
		reload_cart_cost(cart)
		return cart


# def remove_from_cart_view(request):
# 	cart=get_cart(request)

# 	product_slug=request.GET.get('product_slug')
# 	cart.remove_from_cart(product_slug)
# 	reload_cart_cost(cart)
# 	return JsonResponse({'cart_total': cart.items.count(),
# 		'cart_total_price': cart.cart_total,})
def change_item_qty(request):
	cart=get_cart(request)
	qty = request.GET.get('qty')
	item_id = request.GET.get('item_id')
	cart.change_qty(qty, item_id)
	cart_item = CartItem.objects.get(id=int(item_id))
	return JsonResponse(
		{'cart_total': cart.items.count(), 
		'item_total': cart_item.item_total,
		'cart_total_price': cart.cart_total})


def order_create_view(request):
	cart=get_cart(request)
	form = OrderForm(request.POST or None)
	categories = Category.objects.all()
	context = {
		'form': form,
		'cart': cart,
		'categories': categories
	}
	return render(request, 'ecomapp/order.html', context)


def make_order_view(request):
	cart=get_cart(request)
		
	form = OrderForm(request.POST or None)
	categories = Category.objects.all()

	if form.is_valid():

		name = form.cleaned_data['name']
		last_name = form.cleaned_data['last_name']
		phone = form.cleaned_data['phone']
		buying_type = form.cleaned_data['buying_type']
		address = form.cleaned_data['address']
		comments = form.cleaned_data['comments']
		new_order = Order.objects.create(
			user=request.user,
			items=cart,
			total=cart.cart_total,
			first_name=name,
			last_name=last_name,
			phone=phone,
			address=address,
			buying_type=buying_type,
			comments=comments
			)

		del request.session['cart_id']
		del request.session['total']

		return HttpResponseRedirect(reverse('thank_you'))
	return render(request, 'ecomapp/order.html', {'categories': categories})
def account_view(request):
	try:
		order = Order.objects.filter(user=request.user).order_by('-id')

	except:

		return HttpResponseRedirect(reverse('registration'))

	categories = Category.objects.all()
	context = {
		'order': order,
		'categories': categories
	}

	return render(request, 'ecomapp/account.html', context)

def registration_view(request):

	form = RegistrationForm(request.POST or None)
	categories = Category.objects.all()

	if form.is_valid():
		new_user = form.save(commit=False)
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		email = form.cleaned_data['email']
		first_name = form.cleaned_data['first_name']
		last_name = form.cleaned_data['last_name']
		new_user.username = username
		new_user.set_password(password)
		new_user.first_name = first_name
		new_user.last_name = last_name
		new_user.email = email
		new_user.save()
		login_user = authenticate(username=username, password=password)
		
		if login_user:
			
			login(request, login_user)
			return HttpResponseRedirect(reverse('base'))
	context = {
		'form': form,
		'categories': categories
	}
	return render(request, 'ecomapp/registration.html', context)


def login_view(request):
	form = LoginForm(request.POST or None)
	categories = Category.objects.all()
	if form.is_valid():
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		login_user = authenticate(username=username, password=password)
		if login_user:
			login(request, login_user)
			return HttpResponseRedirect(reverse('base'))
	context = {
		'form': form,
		'categories': categories
	}
	return render(request, 'ecomapp/login.html', context)

ecomapp/templates/ecomapp/account.html
{% extends 'ecomapp/base.html' %}


{% block content %}

<h3 class="text-center">Личный кабинет пользователя {{ request.user }}</h3>
<hr>
<h4 class='text-center'>Ваши заказы</h4>
<table class='table'>
<tr style='background:lightblue;'>
	<td class='text-center'>Номер заказа</td>
	<td class='text-center'>Дата заказа</td>
	<td class='text-center'>Статус заказа</td>
	<td class='text-center'>Стоимость заказа</td>
	<td class='text-center'>Детали заказа</td>
	<td></td>
</tr>
{% for item in order %}
<tr>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.id }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.date }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.status }}</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.total }} руб.</td>
	<td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
</tr>
{% endfor %}
</table>
<!-- Button trigger modal -->

<!-- Modal -->
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Заказ № {{ item.id }}</h4>
      </div>
      <div class="modal-body">
      <h3>Товар</h3>
        <table class='table'>
        	{% for order_item in item.items.items.all %}
	        	<tr>
	       			<td>{{ order_item.product.title }}</td>
	       			<td>{{ order_item.qty }} шт.</td>
	       			<td>{{ order_item.item_total }} руб.</td>
	        	</tr>
        	{% endfor %}
        		 <tr>
	        		<td></td>
	        		<td>Итого</td>
	        		<td><strong>{{ item.items.cart_total }} руб.</strong></td>
	        	</tr>
        </table>
   		<h3>Заказчик</h3>
   		 <p>Имя: {{ item.first_name }}</p>
   		 <p>Фамилия: {{ item.last_name }}</p>
   		 <p>Телефон: {{ item.phone }}</p>
   		 <h3>Тип доставки</h3>
   		 <p>{% if item.buying_type == 'self' %} Самовывоз {% else %}Доставка{% endif %}</p>
   		 <p>{% if item.buying_type == 'delivery' %} {{ item.address }}{% endif %}</p>
   		 <h3>Комментарии к заказу</h3>
   		 <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

ecomapp/templates/ecomapp/cart.html
{% extends 'ecomapp/base.html' %}

{% load static %}

{% block content %}
<h3 class='text-center'>Ваша корзина</h3>
<br>
{% if cart.items.count > 0 %}
<div class='my-cart'>
<table class='table'>
<tr>
	<td class='text-center'><strong>Товар</strong></td>
	<td class='text-center'><strong>Кол-во</strong></td>
	<td class='text-center'><strong>Цена</strong></td>
	<td class='text-center'></td>
</tr>
{% for item in cart.items.all %}
<tr class='cart-item-{{ item.product.id }}'>
	<td class='text-center'>{{ item.product.title }}</td>
	<td class="text-center">
		<form action='' method='GET'>
			<input type='number' name='qty' class='cart-item-qty' data-id='{{ item.id }}' value='{{ item.qty }}' min='1' style='width: 50px;'>
		</form>
	</td>
	<td class='text-center' id='cart-item-total-{{ item.id }}'>{{ item.item_total }} руб.</td>
	<td class='text-center'><a href='#' class='remove_from_cart' data-slug='{{ item.product.slug }}' data-id='{{ item.product.id }}'><button class='btn btn-default'>Удалить из корзины</button></a></td>
</tr>
{% endfor %}
<tr>
	<td></td>
	<td class='text-center'> <strong>Итого: </strong></td>
	<td class='text-center' id='cart-total-price'><strong>{{ cart.cart_total }} руб.</strong></td>
	<td class='text-center'></td>
</tr>
</table>
<br>
<a href='{% url "checkout" %}' class='float-right mx-5'><button class='btn btn-info'>Предварительный заказ</button></a>
</div>
<h3 class='cart-empty'></h3>
{% else %}
<h3 class='text-center'>Ваша корзина пуста</h3>
{% endif %}
<script src="{% static 'js/jquery.js' %}"></script>
<script>
$(document).ready(function(){
	$('.cart-empty').css('display', 'none')
	$('.remove_from_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
		item_product_id = $(this).attr('data-id')
		data = {
			product_slug: product_slug
		}		

		$.ajax({
			type: "GET",
			url: '{% url "remove_from_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
				$('.cart-item-'+item_product_id).css('display', 'none')
				$('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
				if(parseInt(data.cart_total) == 0){
					$('.my-cart').css('display', 'none')
					$('.cart-empty').css('display', 'block')
					$('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
				}
			}
		})
	})
})

$(document).ready(function(){
	$('.cart-item-qty').on('click', function(){
		qty = $(this).val()
		item_id = $(this).attr('data-id')
		data = {
			qty: qty,
			item_id: item_id
		}
		$.ajax({
			type: "GET",
			url: '{% url "change_item_qty" %}',
			data: data,
			success: function(data){
				$('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
				$('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' руб. </strong>')
			}
		})
	})
})
</script>
{% endblock content %}

ecomapp/templates/ecomapp/category.html
{% extends 'ecomapp/base.html' %}

{% load static %}
{% block content %}
<div class="row">
<div class='col-sm-12 text-center'>
<h2>{{ category.title }}</h2>
<hr>
<div class="row">
<div class='col-sm-12'>
	<div class="row">
<div class='col-sm-8'>
<div class="row">
{% for product in products_of_category %}

<div class='col-sm-4' style='height: 400px;'>
<a href='{{ product.get_absolute_url }}'><img src='{{ product.image.url }}' style='width:100%; height: 180px;'></a>
<h4 class='text-center'>{{ product.title }}</h4>
<p class='text-center' style='font-size:20px;'>Цена: <strong>{{ product.price }} руб.</strong></p>
{% if request.user.is_authenticated %}<a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a>{% endif %}
<br><br>
{% if not request.user.is_authenticated %}<p class='text-center'>Заказывать товар могут только авторизированные пользователи. Пожалуйста, <a href='{% url "login" %}'>войдите</a> или <a href='{% url "registration" %}'>зарегистрируйтесь</a></p>{% endif %}
</div>

{% endfor %}
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>

{% endblock content %}

ecomapp/templates/ecomapp/checkout.html
{% extends 'ecomapp/base.html' %}


{% block content %}
<h3 class='text-center'>Ваш предварительный заказ</h3>
<br>
<table class='table'>
<tr>
	<td class='text-center'><strong>Товар</strong></td>
	<td class='text-center'><strong>Кол-во</strong></td>
	<td class='text-center'><strong>Цена</strong></td>
	<td class='text-center'></td>
</tr>
{% for item in cart.items.all %}
<tr>
	<td class='text-center'>{{ item.product.title }}</td>
	<td class="text-center">{{ item.qty }}</td>
	<td class='text-center'>{{ item.item_total }} руб.</td>
	<td></td>
</tr>
{% endfor %}
<tr>
	<td></td>
	<td class='text-center'> <strong>Итого: </strong></td>
	<td class='text-center'><strong>{{ cart.cart_total }} руб.</strong></td>
	<td class='text-center'></td>
</tr>
</table>
<div class="mx-5">
<a href='{% url "create_order" %}' class='float-right'><button class='btn btn-success'>Оформить заказ</button></a></div>
{% endblock content %}

ecomapp/templates/ecomapp/login.html
{% extends 'ecomapp/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Авторизация</h3>
<hr>
<div class="row">
<div class='col-sm-8 col-sm-offset-2 ml-5'>
<form action='' method='POST'>
	{% csrf_token %}
	{{ form|crispy }}
	<input type='submit' class='btn btn-success btn-block' value="Войти в систему">
</form>
</div>
</div>
{% endblock content %}

ecomapp/templates/ecomapp/order.html
{% extends 'ecomapp/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Оформление заказа</h3>
<hr>
<form action='{% url "make_order" %}' method="POST">
	{% csrf_token %}
	<div class="container">
	<div class="row">
	<div class='col-sm-4'>
		{{ form.name|as_crispy_field }}
	</div>
	<div class='col-sm-4'>
		{{ form.last_name|as_crispy_field }}
	</div>
	<div class='col-sm-4'>
		{{ form.phone|as_crispy_field }}
	</div>
	</div>
	{{ form.buying_type|as_crispy_field }}
	{{ form.address|as_crispy_field }}
	{{ form.date|as_crispy_field }}
	{{ form.comments|as_crispy_field }}
	<input type='submit' class='btn btn-success' value='Оформить заказ'>
	</div>
</form>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
	$(document).ready(function(){
		$('#div_id_address').css('display', 'none')
		$('#id_buying_type').on('click', function(){
			buying_type = $(this).val()
			if(buying_type == 'delivery'){
				$('#div_id_address').css('display', 'block')
			}else{
				$('#div_id_address').css('display', 'none')
			}
		})
		$('#id_date_month').css('width', '100px')
		$('#id_date_month').css('display', 'inline')
		$('#id_date_year').css('width', '100px')
		$('#id_date_year').css('display', 'inline')
		$('#id_date_day').css('width', '70px')
		$('#id_date_day').css('display', 'inline')
	});

</script>
{% endblock content %}
{% block footer %}
    
{% endblock footer %}

ecomapp/templates/ecomapp/product.html
{% extends 'ecomapp/base.html' %}

{% load static %}
{% block content %}

<div class="container mt-3">
  <div class="row">
    <div class="col-sm"><img src="{{ product.image.url }}" alt="" style='width: 80%; height: 350px;'> </div>
  	<div class="col-sm-8"> 
  		<h3 class="ml-3">aaa{{product.title}}</h3>
<p>{{product.description}} 
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi vero cumque deserunt quo, neque consectetur animi illum expedita, voluptatibus tenetur dolor unde autem reprehenderit, accusamus consequuntur. Mollitia, tempore tempora illo.</p>
<hr>
<p> Price {{product.price}}</p>
{% if request.user.is_authenticated %}<a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a>{% endif %}
<br><br>
{% if not request.user.is_authenticated %}<p class='text-center'>Заказывать товар могут только авторизированные пользователи. Пожалуйста, <a href='{% url "login" %}'>войдите</a> или <a href='{% url "registration" %}'>зарегистрируйтесь</a></p>{% endif %}
</div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script>
$(document).ready(function(){
	$('.add_to_cart').on('click', function(e){
		e.preventDefault()
		product_slug = $(this).attr('data-slug')
		data = {
			product_slug: product_slug
		}
		$.ajax({
			type: "GET",
			url: '{% url "add_to_cart" %}',
			data: data,
			success: function(data){
				$("#cart_count").html(data.cart_total)
			}
		})
	})
});
</script>
{% endblock content %}

ecomapp/templates/ecomapp/registration.html
{% extends 'ecomapp/base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class='text-center'>Регистрация нового пользователя</h3>
<div class="row ml-5 justify-content-center">
<div class='col-sm-offset-2'>
<hr>
<form action='' method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type='submit' class='btn btn-success btn-block' value='Зарегистрироваться'>
</form>
</div>
</div>

{% endblock content %}